/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Thankyou4bhkRouteImport } from './routes/thankyou-4bhk'
import { Route as Picasa4bhkRouteImport } from './routes/picasa-4bhk'
import { Route as IndexRouteImport } from './routes/index'

const Thankyou4bhkRoute = Thankyou4bhkRouteImport.update({
  id: '/thankyou-4bhk',
  path: '/thankyou-4bhk',
  getParentRoute: () => rootRouteImport,
} as any)
const Picasa4bhkRoute = Picasa4bhkRouteImport.update({
  id: '/picasa-4bhk',
  path: '/picasa-4bhk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/picasa-4bhk': typeof Picasa4bhkRoute
  '/thankyou-4bhk': typeof Thankyou4bhkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/picasa-4bhk': typeof Picasa4bhkRoute
  '/thankyou-4bhk': typeof Thankyou4bhkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/picasa-4bhk': typeof Picasa4bhkRoute
  '/thankyou-4bhk': typeof Thankyou4bhkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/picasa-4bhk' | '/thankyou-4bhk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/picasa-4bhk' | '/thankyou-4bhk'
  id: '__root__' | '/' | '/picasa-4bhk' | '/thankyou-4bhk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Picasa4bhkRoute: typeof Picasa4bhkRoute
  Thankyou4bhkRoute: typeof Thankyou4bhkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thankyou-4bhk': {
      id: '/thankyou-4bhk'
      path: '/thankyou-4bhk'
      fullPath: '/thankyou-4bhk'
      preLoaderRoute: typeof Thankyou4bhkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picasa-4bhk': {
      id: '/picasa-4bhk'
      path: '/picasa-4bhk'
      fullPath: '/picasa-4bhk'
      preLoaderRoute: typeof Picasa4bhkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Picasa4bhkRoute: Picasa4bhkRoute,
  Thankyou4bhkRoute: Thankyou4bhkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
